description: 'Полная синхронизация: devices → interfaces → IP → inventory → cables'
enabled: true
id: default
name: Full Sync
steps:
- depends_on: []
  enabled: true
  id: sync_devices
  options: {}
  target: devices
  type: sync
- depends_on:
  - sync_devices
  enabled: true
  id: sync_interfaces
  options:
    cleanup: true
  target: interfaces
  type: sync
- depends_on:
  - sync_interfaces
  enabled: true
  id: sync_ip_addresses
  options:
    cleanup: true
    update_existing: true
  target: ip_addresses
  type: sync
- depends_on:
  - sync_devices
  enabled: true
  id: sync_inventory
  options:
    cleanup: true
  target: inventory
  type: sync
- depends_on:
  - sync_interfaces
  enabled: true
  id: sync_cables
  options:
    cleanup: true
  target: cables
  type: sync
